
import { GamerProfile, Message, BackgroundItem } from './types';

export const gamerProfiles: GamerProfile[] = [
  {
    id: 1,
    name: 'אורן',
    age: 22,
    image: 'https://images.unsplash.com/photo-1555952517-2e8e729e0b44?q=80&w=1964&auto=format&fit=crop',
    bio: 'מחפש סקוואד רגוע לערב. בעיקר משחק Warzone אבל זורם גם על דברים אחרים.',
    games: [
      { name: 'Call of Duty: Warzone', icon: 'fa-crosshairs', lookingFor: 'מחפש סקוואד רגוע לערב, בעיקר Rebirth.' },
      { name: 'FIFA', icon: 'fa-futbol', lookingFor: 'מחפש יריבים למשחקי Pro Clubs.' },
    ],
    platforms: ['PlayStation 5', 'PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 2,
    name: 'יעל',
    age: 25,
    image: 'https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?q=80&w=2053&auto=format&fit=crop',
    bio: 'גיימרת קז\'ואל שאוהבת משחקי אינדי ו-co-op.',
    games: [
      { name: 'Minecraft', icon: 'fa-cube', lookingFor: 'מחברת שותפים לבניית עולם Survival ארוך טווח.' },
    ],
    platforms: ['PC', 'Nintendo Switch'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 3,
    name: 'עמית',
    age: 24,
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן FIFA תחרותי. מחפש שותף ל-Ultimate Team או יריבים לאימון.',
    games: [
      { name: 'FIFA 24', icon: 'fa-futbol', lookingFor: 'יריבים לרמה גבוהה בלבד.' },
      { name: 'Rocket League', icon: 'fa-car', lookingFor: 'מחפש שותף ל-2v2 בדרגת Diamond.' },
    ],
    platforms: ['PlayStation 5'],
    skillLevel: 'תחרותי',
  },
  {
    id: 4,
    name: 'נועה',
    age: 21,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1976&auto=format&fit=crop',
    bio: 'מכורה ל-Valorant. מחפשת קבוצה רצינית לעלות בראנקים.',
    games: [
      { name: 'Valorant', icon: 'fa-gun', lookingFor: 'מחפשת Duelist או Initiator לסקוואד קבוע.' },
      { name: 'CS2', icon: 'fa-crosshairs', lookingFor: 'זורמת על משחקי פרימייר בערב.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 5,
    name: 'גיא',
    age: 30,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974&auto=format&fit=crop',
    bio: 'גיימר "זקן" שאוהב משחקי אסטרטגיה וסימולטורים. מחפש אנשים רגועים לשיחות תוך כדי משחק.',
    games: [
      { name: 'Civilization VI', icon: 'fa-earth-americas', lookingFor: 'משחקי Multi ארוכים בסופי שבוע.' },
      { name: 'Flight Simulator', icon: 'fa-plane', lookingFor: 'טיסות משותפות ב-VATSIM.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 6,
    name: 'דנה',
    age: 23,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1974&auto=format&fit=crop',
    bio: 'חובבת RPG מושבעת. כרגע חזק ב-Baldur\'s Gate 3 ומחפשת שותפים לקמפיין.',
    games: [
      { name: 'Baldur\'s Gate 3', icon: 'fa-dragon', lookingFor: 'שותפים לקמפיין Co-op בדרגת Honor.' },
      { name: 'Elden Ring', icon: 'fa-khanda', lookingFor: 'עזרה בבוסים או סתם שיטוט משותף.' },
    ],
    platforms: ['PC', 'Xbox Series X'],
    skillLevel: 'תחרותי',
  },
  {
    id: 7,
    name: 'איתי',
    age: 27,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן NBA2K ו-Madden. מחפש ליגות ישראליות פעילות.',
    games: [
      { name: 'NBA 2K24', icon: 'fa-basketball', lookingFor: 'מחפש קבוצת Pro-Am.' },
    ],
    platforms: ['PlayStation 5', 'Xbox Series X'],
    skillLevel: 'תחרותי',
  },
  {
    id: 8,
    name: 'שלי',
    age: 19,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1964&auto=format&fit=crop',
    bio: 'אוהבת משחקי אימה ו-survival. מחפשת מישהו שיצרח איתי ב-Phasmophobia.',
    games: [
      { name: 'Phasmophobia', icon: 'fa-ghost', lookingFor: 'מחפשת ציידי רוחות אמיצים.' },
      { name: 'Dead by Daylight', icon: 'fa-skull', lookingFor: 'מחפשת סורבייבורס לסקוואד.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 9,
    name: 'רון',
    age: 26,
    image: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?q=80&w=1974&auto=format&fit=crop',
    bio: 'נהג מרוצים וירטואלי. מחפש קהילות Sim Racing בישראל.',
    games: [
      { name: 'F1 23', icon: 'fa-car-side', lookingFor: 'מחפש ליגות נהיגה נקיות.' },
      { name: 'Assetto Corsa', icon: 'fa-gauge-high', lookingFor: 'דריפטים ואימוני מסלול.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 10,
    name: 'מאיה',
    age: 22,
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי "Cozy" ועיצוב. מחפשת חברים ל-Animal Crossing או Stardew Valley.',
    games: [
      { name: 'Animal Crossing', icon: 'fa-leaf', lookingFor: 'ביקורים באי וחלופת מתנות.' },
      { name: 'Stardew Valley', icon: 'fa-seedling', lookingFor: 'בניית חווה משותפת.' },
    ],
    platforms: ['Nintendo Switch'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 11,
    name: 'עידו',
    age: 20,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן TFT שמנסה להגיע ל-Challenger. מחפש אנשים לשיחות על אסטרטגיה ובילדים.',
    games: [
      { name: 'Teamfight Tactics', icon: 'fa-chess-board', lookingFor: 'שותפים למשחקי ראנקד ושיחות דיסקורד.' },
    ],
    platforms: ['PC', 'Mobile'],
    skillLevel: 'תחרותי',
  },
  {
    id: 12,
    name: 'שיר',
    age: 28,
    image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=1974&auto=format&fit=crop',
    bio: 'גיימרת ותיקה. חולה על Overwatch 2 ומשחקי תפקידים.',
    games: [
      { name: 'Overwatch 2', icon: 'fa-shield-halved', lookingFor: 'מחפשת Tank שיודע מה הוא עושה.' },
      { name: 'Diablo IV', icon: 'fa-fire-burner', lookingFor: 'ריצות דאנג׳נים בערבים.' },
    ],
    platforms: ['PC', 'PlayStation 5'],
    skillLevel: 'תחרותי',
  },
  {
    id: 13,
    name: 'דניאל',
    age: 18,
    image: 'https://images.unsplash.com/photo-1506863530036-1efeddceb993?q=80&w=1944&auto=format&fit=crop',
    bio: 'צעיר, מהיר וחצוף. שחקן Valorant מקצועי בנשמה.',
    games: [
      { name: 'Valorant', icon: 'fa-gun', lookingFor: 'סקוואד רציני לטיפוס בראנקים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 14,
    name: 'רתם',
    age: 29,
    image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת את השקט שלי עם משחקי בנייה. מחפשת מישהו לבנות איתו אימפריה ב-Satisfactory.',
    games: [
      { name: 'Satisfactory', icon: 'fa-industry', lookingFor: 'מישהו עם סבלנות לבניית מפעלים ענקיים.' },
      { name: 'Factorio', icon: 'fa-gears', lookingFor: 'ייעול קווי ייצור.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 15,
    name: 'אלון',
    age: 32,
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=2048&auto=format&fit=crop',
    bio: 'אבא לגיימרים קטנים. משחק בלילה כשהם ישנים. מחפש סקוואד בוגר.',
    games: [
      { name: 'World of Warcraft', icon: 'fa-wand-sparkles', lookingFor: 'גילדה רגועה לריידים של פעם בשבוע.' },
      { name: 'Hearthstone', icon: 'fa-cards-diamond', lookingFor: 'יריבים לקרבות ידידותיים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 16,
    name: 'טל',
    age: 24,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן FPS בדם. מחפש אנשים ל-Apex Legends.',
    games: [
      { name: 'Apex Legends', icon: 'fa-person-running', lookingFor: 'מחפש Wraith או Horizon מנוסים.' },
    ],
    platforms: ['PC', 'Xbox'],
    skillLevel: 'תחרותי',
  },
  {
    id: 17,
    name: 'בר',
    age: 21,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1974&auto=format&fit=crop',
    bio: 'סטודנטית שצריכה הפסקה מהלימודים. משחקת הכל מהכל.',
    games: [
      { name: 'Among Us', icon: 'fa-mask', lookingFor: 'קבוצה למשחקים מלאים בצחוק.' },
      { name: 'Fall Guys', icon: 'fa-person-falling', lookingFor: 'מישהו להפסיד איתו בכבוד.' },
    ],
    platforms: ['Mobile', 'PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 18,
    name: 'עומר',
    age: 25,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974&auto=format&fit=crop',
    bio: 'מעריץ מושבע של ז׳אנר ה-Soulslike. מחפש מישהו שיעזור לי בבוסים.',
    games: [
      { name: 'Dark Souls 3', icon: 'fa-khanda', lookingFor: 'עזרה בבוסים וחקירה משותפת.' },
      { name: 'Lies of P', icon: 'fa-clock', lookingFor: 'שיחות על הסיפור והמכניקה.' },
    ],
    platforms: ['PC', 'PlayStation 5'],
    skillLevel: 'תחרותי',
  },
  {
    id: 19,
    name: 'אביב',
    age: 23,
    image: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=1978&auto=format&fit=crop',
    bio: 'שחקנית תחרותית ב-League of Legends. Main Support מחפשת ADC.',
    games: [
      { name: 'League of Legends', icon: 'fa-shield', lookingFor: 'מחפשת ADC בדרגת Diamond ומעלה.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 20,
    name: 'ספיר',
    age: 27,
    image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי פאזלים ומסתורין. מחפשת מישהו לפתור איתו תעלומות.',
    games: [
      { name: 'Portal 2', icon: 'fa-door-open', lookingFor: 'שותף ל-Co-op שלא מתעצבן מהר.' },
      { name: 'It Takes Two', icon: 'fa-people-arrows', lookingFor: 'מישהו לסשן משחקים ארוך.' },
    ],
    platforms: ['PC', 'Nintendo Switch'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 21,
    name: 'ליאור',
    age: 35,
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070&auto=format&fit=crop',
    bio: 'גיימר רטרו. אוהב את הקלאסיקות ומחפש אנשים שזוכרים את ה-NES.',
    games: [
      { name: 'Street Fighter 6', icon: 'fa-hand-fist', lookingFor: 'יריבים לקרבות קלאסיים.' },
      { name: 'Tekken 8', icon: 'fa-burst', lookingFor: 'מישהו להתאמן איתו.' },
    ],
    platforms: ['PC', 'Arcade'],
    skillLevel: 'תחרותי',
  },
  {
    id: 22,
    name: 'הילה',
    age: 22,
    image: 'https://images.unsplash.com/photo-1541216970279-affbfdd55aa8?q=80&w=1974&auto=format&fit=crop',
    bio: 'מכורה למשחקי בניית ערים וניהול. מחפשת קהילות של Cities Skylines.',
    games: [
      { name: 'Cities Skylines II', icon: 'fa-city', lookingFor: 'שיתוף טיפים לעיצוב ערים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 23,
    name: 'יונתן',
    age: 26,
    image: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן FPS ו-Survival. מחפש סקוואד ל-Rust או DayZ.',
    games: [
      { name: 'Rust', icon: 'fa-radiation', lookingFor: 'מחפש קבוצה לבניית בסיס והגנה.' },
      { name: 'DayZ', icon: 'fa-biohazard', lookingFor: 'מישהו לשרוד איתו את הלילה.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 24,
    name: 'נועם',
    age: 24,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=2070&auto=format&fit=crop',
    bio: 'אוהבת משחקי מוזיקה וקצב. מחפשת מישהו ל-Beat Saber.',
    games: [
      { name: 'Beat Saber', icon: 'fa-music', lookingFor: 'תחרות ציונים גבוהים.' },
    ],
    platforms: ['VR'],
    skillLevel: 'תחרותי',
  },
  {
    id: 25,
    name: 'תומר',
    age: 31,
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=2070&auto=format&fit=crop',
    bio: 'חובב משחקי לוח דיגיטליים ומשחקי קלפים.',
    games: [
      { name: 'Magic: The Gathering Arena', icon: 'fa-magic', lookingFor: 'יריבים לקרבות קומנדר.' },
      { name: 'Tabletop Simulator', icon: 'fa-table-list', lookingFor: 'קבוצה לערבי משחקי לוח.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 26,
    name: 'עדי',
    age: 19,
    image: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?q=80&w=2070&auto=format&fit=crop',
    bio: 'שחקנית Roblox ו-Fortnite. מחפשת חברים למשחקי Creative.',
    games: [
      { name: 'Fortnite', icon: 'fa-person-rifle', lookingFor: 'מישהו לבנות איתו ב-Creative mode.' },
      { name: 'Roblox', icon: 'fa-cubes', lookingFor: 'חברים למשחקי RP.' },
    ],
    platforms: ['PC', 'Mobile', 'Console'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 27,
    name: 'שי',
    age: 28,
    image: 'https://images.unsplash.com/photo-1512485694743-9c9538b4e6e0?q=80&w=1974&auto=format&fit=crop',
    bio: 'מחפש משחקי קואופרציה מקומיים או אונליין. אוהב את Helldivers 2.',
    games: [
      { name: 'Helldivers 2', icon: 'fa-rocket', lookingFor: 'הפצת דמוקרטיה עם סקוואד רציני.' },
    ],
    platforms: ['PC', 'PlayStation 5'],
    skillLevel: 'תחרותי',
  },
  {
    id: 28,
    name: 'מיכל',
    age: 23,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop',
    bio: 'שחקנית אינדי מושבעת. תמיד מחפשת את הלהיט הבא ב-Steam.',
    games: [
      { name: 'Terraria', icon: 'fa-tree', lookingFor: 'בניית עולם חדש מ-0.' },
      { name: 'Valheim', icon: 'fa-ship', lookingFor: 'שיט משותף וציד בוסים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 29,
    name: 'גל',
    age: 25,
    image: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?q=80&w=2070&auto=format&fit=crop',
    bio: 'שחקן ספורט אלקטרוני. מחפש את האתגר הבא ב-Rocket League.',
    games: [
      { name: 'Rocket League', icon: 'fa-car', lookingFor: 'שותף ל-Ranked בדרגת Grand Champion.' },
    ],
    platforms: ['PC', 'PlayStation 5'],
    skillLevel: 'מקצוען',
  },
  {
    id: 30,
    name: 'רוני',
    age: 20,
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1964&auto=format&fit=crop',
    bio: 'אוהבת את הצד היצירתי של הגיימינג. בונה מפות ומשחקים.',
    games: [
      { name: 'The Sims 4', icon: 'fa-house', lookingFor: 'שיתוף עיצובים ורעיונות.' },
      { name: 'Dreams', icon: 'fa-cloud', lookingFor: 'יצירה משותפת.' },
    ],
    platforms: ['PC', 'PlayStation 4'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 31,
    name: 'לירון',
    age: 23,
    image: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?q=80&w=1974&auto=format&fit=crop',
    bio: 'מחפשת קבוצת Overwatch 2. משחקת בעיקר Support אבל יכולה גם DPS.',
    games: [
      { name: 'Overwatch 2', icon: 'fa-shield-halved', lookingFor: 'סקוואד רציני למשחקי דירוג.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 32,
    name: 'עידן',
    age: 26,
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1974&auto=format&fit=crop',
    bio: 'מכור ל-Elden Ring. עוזר לאנשים לעבור בוסים קשים.',
    games: [
      { name: 'Elden Ring', icon: 'fa-khanda', lookingFor: 'מישהו לעזור לו או לחקור ביחד.' },
    ],
    platforms: ['PC', 'PS5'],
    skillLevel: 'מקצוען',
  },
  {
    id: 33,
    name: 'שחר',
    age: 21,
    image: 'https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Valorant מקצועי בנשמה. מחפש לעלות ל-Radiant.',
    games: [
      { name: 'Valorant', icon: 'fa-gun', lookingFor: 'קבוצה קבועה לאימונים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 34,
    name: 'אביב',
    age: 24,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי אסטרטגיה וקלפים. מחפשת שותפים ל-Hearthstone.',
    games: [
      { name: 'Hearthstone', icon: 'fa-cards', lookingFor: 'יריבים לקרבות ידידותיים.' },
    ],
    platforms: ['Mobile', 'PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 35,
    name: 'אורי',
    age: 19,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Rocket League בדרגת Champion. מחפש שותף ל-2v2.',
    games: [
      { name: 'Rocket League', icon: 'fa-car', lookingFor: 'שותף רציני לעלייה בדרגות.' },
    ],
    platforms: ['PC', 'Xbox'],
    skillLevel: 'תחרותי',
  },
  {
    id: 36,
    name: 'מעיין',
    age: 22,
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1974&auto=format&fit=crop',
    bio: 'חולה על משחקי אינדי ופאזלים. מחפשת המלצות למשחקים חדשים.',
    games: [
      { name: 'Stardew Valley', icon: 'fa-seedling', lookingFor: 'שותפים לבניית חווה.' },
    ],
    platforms: ['Switch'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 37,
    name: 'נדב',
    age: 25,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Warzone אגרסיבי. אוהב Bounty hunting.',
    games: [
      { name: 'Warzone', icon: 'fa-gun', lookingFor: 'סקוואד שלא מפחד להיכנס לקרבות.' },
    ],
    platforms: ['PS5'],
    skillLevel: 'תחרותי',
  },
  {
    id: 38,
    name: 'קארין',
    age: 20,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת League of Legends בדרגת Gold. מחפשת ללמוד עוד.',
    games: [
      { name: 'League of Legends', icon: 'fa-shield', lookingFor: 'מישהו ללמוד ממנו או לשחק בכיף.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 39,
    name: 'דניאל',
    age: 27,
    image: 'https://images.unsplash.com/photo-1506863530036-1efeddceb993?q=80&w=1974&auto=format&fit=crop',
    bio: 'מעריץ של משחקי ספורט. מחפש ליגת NBA 2K פעילה.',
    games: [
      { name: 'NBA 2K', icon: 'fa-basketball', lookingFor: 'קבוצה ל-Pro-Am.' },
    ],
    platforms: ['Xbox'],
    skillLevel: 'תחרותי',
  },
  {
    id: 40,
    name: 'איה',
    age: 23,
    image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי אימה ו-survival. מחפשת מישהו שלא יפחד ב-Dead by Daylight.',
    games: [
      { name: 'Dead by Daylight', icon: 'fa-skull', lookingFor: 'קבוצת סורבייבורס.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 41,
    name: 'ברק',
    age: 29,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן אסטרטגיה ותיק. מחפש יריבים ל-StarCraft II.',
    games: [
      { name: 'StarCraft II', icon: 'fa-rocket', lookingFor: 'משחקי לאדר רציניים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 42,
    name: 'רוני',
    age: 18,
    image: 'https://images.unsplash.com/photo-1512485694743-9c9538b4e6e0?q=80&w=1974&auto=format&fit=crop',
    bio: 'רק התחלתי לשחק Valorant. מחפשת אנשים סבלניים.',
    games: [
      { name: 'Valorant', icon: 'fa-gun', lookingFor: 'מישהו ללמד אותי את הבסיס.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 43,
    name: 'מתן',
    age: 26,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=1974&auto=format&fit=crop',
    bio: 'חובב משחקי מרוצים. מחפש קהילת Forza Horizon.',
    games: [
      { name: 'Forza Horizon 5', icon: 'fa-car', lookingFor: 'טיולים משותפים ומרוצים.' },
    ],
    platforms: ['Xbox', 'PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 44,
    name: 'הילה',
    age: 24,
    image: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי RPG. כרגע בתוך Cyberpunk 2077.',
    games: [
      { name: 'Cyberpunk 2077', icon: 'fa-microchip', lookingFor: 'שיחות על הסיפור והבילדים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 45,
    name: 'יוסי',
    age: 31,
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן WoW ותיק. מחפש גילדה לריידים.',
    games: [
      { name: 'World of Warcraft', icon: 'fa-dragon', lookingFor: 'קבוצה קבועה לריידים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 46,
    name: 'סיוון',
    age: 22,
    image: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת Apex Legends. אוהבת לשחק אגרסיבי.',
    games: [
      { name: 'Apex Legends', icon: 'fa-person-running', lookingFor: 'סקוואד רציני למשחקי ראנקד.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 47,
    name: 'גלעד',
    age: 28,
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן CS2 מיומן. מחפש קבוצה לטורנירים.',
    games: [
      { name: 'CS2', icon: 'fa-crosshairs', lookingFor: 'קבוצה רצינית לאימונים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 48,
    name: 'ליטל',
    age: 21,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי בנייה וניהול. מחפשת שותפים ל-Terraria.',
    games: [
      { name: 'Terraria', icon: 'fa-tree', lookingFor: 'בניית עולם חדש ביחד.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 49,
    name: 'ערן',
    age: 25,
    image: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחק FIFA בדרגת Elite. מחפש יריבים ראויים.',
    games: [
      { name: 'FIFA 24', icon: 'fa-futbol', lookingFor: 'משחקי ידידות ברמה גבוהה.' },
    ],
    platforms: ['PS5'],
    skillLevel: 'מקצוען',
  },
  {
    id: 50,
    name: 'טליה',
    age: 19,
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת Roblox בכיף שלה. מחפשת חברים חדשים.',
    games: [
      { name: 'Roblox', icon: 'fa-gamepad', lookingFor: 'מישהו לשחק איתו בכל מיני מודים.' },
    ],
    platforms: ['Mobile'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 51,
    name: 'רון',
    age: 33,
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן סימולטורים. אוהב את Euro Truck Simulator 2.',
    games: [
      { name: 'Euro Truck Simulator 2', icon: 'fa-truck', lookingFor: 'קונבויים משותפים.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 52,
    name: 'סופי',
    age: 24,
    image: 'https://images.unsplash.com/photo-1541216970279-affbfdd55aa8?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי פנטזיה. כרגע ב-Baldur\'s Gate 3.',
    games: [
      { name: 'Baldur\'s Gate 3', icon: 'fa-dragon', lookingFor: 'קבוצה לקמפיין Co-op.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 53,
    name: 'ניר',
    age: 26,
    image: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Rainbow Six Siege. מחפש סקוואד טקטי.',
    games: [
      { name: 'Rainbow Six Siege', icon: 'fa-shield', lookingFor: 'קבוצה שמתקשרת היטב.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 54,
    name: 'שלי',
    age: 21,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת Fortnite בכיף. אוהבת לעשות קווסטים.',
    games: [
      { name: 'Fortnite', icon: 'fa-person-rifle', lookingFor: 'שותף למשחקי קז\'ואל.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 55,
    name: 'ליאור',
    age: 30,
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=1974&auto=format&fit=crop',
    bio: 'חובב משחקי לוח דיגיטליים. אוהב את Tabletop Simulator.',
    games: [
      { name: 'Tabletop Simulator', icon: 'fa-table-list', lookingFor: 'קבוצה לערבי משחקי לוח.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 56,
    name: 'אנה',
    age: 23,
    image: 'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת Destiny 2. מחפשת קבוצה לריידים.',
    games: [
      { name: 'Destiny 2', icon: 'fa-rocket', lookingFor: 'קבוצה פעילה לתוכן אנדגיימ.' },
    ],
    platforms: ['PC'],
    skillLevel: 'תחרותי',
  },
  {
    id: 57,
    name: 'אלעד',
    age: 27,
    image: 'https://images.unsplash.com/photo-1512485694743-9c9538b4e6e0?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Dota 2 ותיק. מחפש סקוואד רציני.',
    games: [
      { name: 'Dota 2', icon: 'fa-chess-knight', lookingFor: 'קבוצה למשחקי דירוג.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 58,
    name: 'נעה',
    age: 20,
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1974&auto=format&fit=crop',
    bio: 'משחקת Minecraft בשרתים שונים. אוהבת לבנות.',
    games: [
      { name: 'Minecraft', icon: 'fa-cube', lookingFor: 'חברים לבנייה משותפת.' },
    ],
    platforms: ['PC'],
    skillLevel: 'קז\'ואל',
  },
  {
    id: 59,
    name: 'ינאי',
    age: 25,
    image: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?q=80&w=1974&auto=format&fit=crop',
    bio: 'שחקן Rocket League מיומן. מחפש שותף ל-3v3.',
    games: [
      { name: 'Rocket League', icon: 'fa-car', lookingFor: 'קבוצה לתחרויות.' },
    ],
    platforms: ['PC'],
    skillLevel: 'מקצוען',
  },
  {
    id: 60,
    name: 'לימור',
    age: 22,
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1974&auto=format&fit=crop',
    bio: 'אוהבת משחקי מוזיקה. מחפשת מישהו ל-Beat Saber.',
    games: [
      { name: 'Beat Saber', icon: 'fa-music', lookingFor: 'מישהו להשוות איתו שיאים.' },
    ],
    platforms: ['VR'],
    skillLevel: 'תחרותי',
  }
];

export const currentUserProfile: GamerProfile = {
    id: 0,
    name: 'ישראל ישראלי',
    age: 26,
    image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=1780&auto=format&fit=crop',
    bannerImage: 'linear-gradient(135deg, #0F172A 0%, #1E293B 100%)',
    avatarBorder: 'linear-gradient(135deg, #6366F1 0%, #22D3EE 100%)',
    bio: 'גיימר בנשמה, מחפש אנשים טובים למשחקים בערב.',
    games: [
      { name: 'Call of Duty: Warzone', icon: 'fa-crosshairs', lookingFor: 'משחק בעיקר בסופ"שים.' },
    ],
    platforms: ['PC', 'PlayStation 5'],
    skillLevel: 'תחרותי',
};

export const backgroundShopItems: BackgroundItem[] = [
  // --- BACKGROUNDS ---
  {
    id: 'color-1',
    name: 'Cyber Purple Neon',
    price: 850,
    previewUrl: 'linear-gradient(135deg, #6366F1 0%, #A855F7 100%)',
    itemType: 'background',
    isAnimated: true,
    rarity: 'Legendary',
    animationClass: 'bg-moving',
    category: 'Cyber'
  },
  {
    id: 'color-2',
    name: 'Electric Cyan',
    price: 1500,
    previewUrl: 'linear-gradient(135deg, #22D3EE 0%, #0EA5E9 100%)',
    itemType: 'background',
    isAnimated: true,
    rarity: 'Legendary',
    animationClass: 'animate-pulse-slow',
    category: 'Cyber'
  },
  {
    id: 'color-3',
    name: 'Dark Matter',
    price: 400,
    previewUrl: '#0F172A',
    itemType: 'background',
    isAnimated: false,
    rarity: 'Common',
    category: 'Cyber'
  },
  {
    id: 'color-4',
    name: 'Deep Space Violet',
    price: 950,
    previewUrl: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 100%)',
    itemType: 'background',
    isAnimated: true,
    rarity: 'Legendary',
    animationClass: 'bg-moving',
    category: 'Space'
  },

  // --- AVATAR BORDERS ---
  {
    id: 'border-1',
    name: 'Gold Royal Ring',
    price: 2500,
    previewUrl: 'linear-gradient(135deg, #F59E0B 0%, #78350F 100%)',
    itemType: 'avatar-border',
    isAnimated: true,
    rarity: 'Legendary',
    animationClass: 'bg-moving',
    category: 'Borders'
  },
  {
    id: 'border-2',
    name: 'Neon Pulse Rose',
    price: 1200,
    previewUrl: 'linear-gradient(135deg, #F43F5E 0%, #881337 100%)',
    itemType: 'avatar-border',
    isAnimated: true,
    rarity: 'Epic',
    animationClass: 'animate-pulse-slow',
    category: 'Borders'
  },
  {
    id: 'border-3',
    name: 'Cyber Cyan Core',
    price: 900,
    previewUrl: 'linear-gradient(135deg, #22D3EE 0%, #0369A1 100%)',
    itemType: 'avatar-border',
    isAnimated: false,
    rarity: 'Rare',
    category: 'Borders'
  },
  {
    id: 'border-4',
    name: 'Poison Ivy Green',
    price: 600,
    previewUrl: 'linear-gradient(135deg, #10B981 0%, #064E3B 100%)',
    itemType: 'avatar-border',
    isAnimated: false,
    rarity: 'Rare',
    category: 'Borders'
  },
  {
    id: 'border-5',
    name: 'Common Gray Rim',
    price: 200,
    previewUrl: '#475569',
    itemType: 'avatar-border',
    isAnimated: false,
    rarity: 'Common',
    category: 'Borders'
  }
];

export const profilesWhoLikedUser: GamerProfile[] = [
    {...gamerProfiles[0], id: 101, name: 'רוני'},
    {...gamerProfiles[1], id: 102, name: 'שני'}
];
export const matchedProfiles: GamerProfile[] = [gamerProfiles[1]];
export const mockConversations: Record<number, Message[]> = {
  2: [
    { id: 1, text: "היי! רוצה לשחק?", senderId: 0, timestamp: "10:00" },
    { id: 2, text: "בטח, מתי?", senderId: 2, timestamp: "10:05" }
  ]
};
